{% set name = "onnxruntime" %}
{% set version = "1.22.0" %}

package:
  name: {{ name|lower }}{{ suffix }}
  version: {{ version }}

source:
  - url: https://github.com/microsoft/onnxruntime/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 08b078eb7afbf376064b2b0f1781e3d78151cac0592988a0c0ec78bf72fde810
    patches:
      - patches/dont-call-pip-on-win.patch                # [win]
      - patches/skip-lora-cuda-test.patch                 # [(ep_variant == "cuda")]
      - patches/skip-custom-op-handler-cuda-test.patch    # [(ep_variant == "cuda")]
      - patches/skip-thread-pool-tests.patch              # [(ep_variant == "cuda")]
      - patches/skip-onnxruntime_shared_lib_test.patch    # [(ep_variant == "cuda")]
      - patches/skip-onnxruntime_test_python.patch        # [(ep_variant == "cuda")]
      - patches/0002-skip-testing-python-iobinding.patch  # [(ep_variant == "cuda")]
      - patches/skip-CudaNhwcTypedTest.patch              # [(ep_variant == "cuda")]
      - patches/skip-CudaNhwcTypedTest-2.patch            # [(ep_variant == "cuda")]
      # Workaround for https://github.com/conda-forge/onnxruntime-feedstock/pull/56#issuecomment-1586080419
      # - patches/windows_workaround_conflict_onnxruntime_dll_system32.patch  # [win]
      # - patches/0001-remove-broken-cuda-moe-test-case.patch                 # [(ep_variant == "cuda")]
      # - patches/skip_custom_op_test_with_cuda.patch                         # [(ep_variant == "cuda")]
      # - patches/fix_cwd_name_on_win.patch                                   # [win]
      - patches/fix-eigen-hash.patch

build:
  number: 0
  skip: true  # [py<310]
  # temporary to not clog up the CI
  skip: true  # [(ep_variant == "cpu")]
  skip: true  # [py>310]
  # string: gpu_cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{PKG_HASH}}_{{ PKG_BUILDNUM }}  # [(ep_variant == "cuda")]
  string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ ep_variant }}
  ignore_run_exports_from:
    - zlib
  ignore_run_exports:
    - numpy
    - libcurl
  entry_points:
    - onnxruntime_test = onnxruntime.tools.onnxruntime_test:main
  missing_dso_whitelist:
    - '**/api-ms-win-core-path-l1-1-0.dll'     # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [(ep_variant == "cuda")]
    - cmake
    - git       # [not win]
    - ninja     # [not win]
    - psutil
  host:
    # GPU requirements
    - cuda-nvcc {{ cuda_compiler_version }}       # [(ep_variant == "cuda")]
    - cudnn {{ cudnn }}                           # [(ep_variant == "cuda")]
    - cuda-version {{ cuda_compiler_version }}    # [(ep_variant == "cuda")]
    - libcublas-dev                               # [(ep_variant == "cuda")]
    - libcusparse-dev                             # [(ep_variant == "cuda")]
    - libcurand-dev                               # [(ep_variant == "cuda")]
    - libcufft-dev                                # [(ep_variant == "cuda")]
    - cuda-cudart-dev                             # [(ep_variant == "cuda")]
    - cuda-nvrtc-dev                              # [(ep_variant == "cuda")]
    # Needed for CUDA profiling
    - cuda-cupti-dev {{ cuda_compiler_version }}  # [(ep_variant == "cuda")]
    - python
    - pip
    - setuptools
    - wheel
    - flake8
    - libdate
    - packaging
    - python-flatbuffers
    - optional-lite
    - zlib {{ zlib }}
    - numpy
    - pybind11 2.13
    - psutil
  run:
    - __cuda  # [linux and (ep_variant == "cuda")]
    - coloredlogs
    # numpy 2.0 sets the min pin to 1.19 and 2.1 sets 1.21 but upstream requires at least 1.21.6
    - numpy >=1.21.6,<3
    - packaging
    - protobuf
    - python
    - python-flatbuffers
    - sympy
  run_constrained:
    - onnxruntime <0a0  # [suffix == "-novec"]

outputs:
  - name: onnxruntime{{ suffix }}
    test:
      imports:
        - onnxruntime
      commands:
        - pip check
        - onnxruntime_test --help
      requires:
        - pip
  - name: onnxruntime{{ suffix }}-cpp
    build:
      string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ ep_variant }}
      run_exports:
        - {{ pin_subpackage('onnxruntime' + suffix + '-cpp', max_pin='x.x.x') }}
    script: install-cpp.sh  # [unix]
    script: install-cpp.bat  # [win]
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}  # [(ep_variant == "cuda")]
      run:
        - __cuda  # [(ep_variant == "cuda")]
      run_constrained:
        - onnxruntime <0a0  # [suffix == "-novec"]
    test:
      requires: 
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
      files:
        - test.cpp
        - run_cpp_test.bat
      commands:
        - test -f $PREFIX/include/onnxruntime/core/session/onnxruntime_cxx_api.h  # [unix]
        - test -f $PREFIX/lib/libonnxruntime${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libonnxruntime_providers_shared${SHLIB_EXT}  # [unix and (ep_variant == "cuda")]
        - test -f $PREFIX/lib/libonnxruntime_providers_cuda${SHLIB_EXT}  # [unix and (ep_variant == "cuda")]
        - if not exist %LIBRARY_INC%\\onnxruntime\\core\\session\\onnxruntime_cxx_api.h exit 1  # [win]
        - if not exist %LIBRARY_LIB%\\onnxruntime_conda.lib exit 1  # [win]
        - if not exist %LIBRARY_BIN%\\onnxruntime_conda.dll exit 1  # [win]
        - if not exist %LIBRARY_LIB%\\onnxruntime_providers_shared.lib exit 1  # [win and (ep_variant == "cuda")]
        - if not exist %LIBRARY_BIN%\\onnxruntime_providers_shared.dll exit 1  # [win and (ep_variant == "cuda")]
        - if not exist %LIBRARY_LIB%\\onnxruntime_providers_cuda.lib exit 1  # [win and (ep_variant == "cuda")]
        - if not exist %LIBRARY_BIN%\\onnxruntime_providers_cuda.dll exit 1  # [win and (ep_variant == "cuda")]
        - $CXX $CXXFLAGS -I$PREFIX/include/ -L$PREFIX/lib/ -lonnxruntime test.cpp                               # [linux]
        - $CXX $CXXFLAGS -I$PREFIX/include/ -L$PREFIX/lib/ -lonnxruntime -Wl,-rpath,$CONDA_PREFIX/lib test.cpp  # [osx]
        - ./a.out  # [unix]
        - call .\run_cpp_test.bat  # [win]

about:
  home: https://onnxruntime.ai
  dev_url: https://github.com/microsoft/onnxruntime
  doc_url: https://onnxruntime.ai/docs
  summary: cross-platform, high performance ML inferencing and training accelerator
  description: |
    ONNX Runtime is a cross-platform machine-learning model accelerator,
    with a flexible interface to integrate hardware-specific libraries.
    ONNX Runtime can be used with models from PyTorch, Tensorflow/Keras,
    TFLite, scikit-learn, and other frameworks.
  license: MIT AND BSL-1.0
  license_family: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - janjagusch
    - jtilly
    - cbourjau
