{% set name = "onnxruntime" %}
{% set version = "1.24.4" %}

package:
  name: {{ name|lower }}{{ suffix }}-split
  version: {{ version }}

source:
  url: https://github.com/microsoft/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0cf4d2ee4392fbb8aedaabc6b2ba11b4a680d1071fa4f75546c2289ca5b404cf
  patches:
    - patches/remove-problematic-win-test.patch  # [win]
    - patches/system-onnxruntime-overcome.patch  # [win]
    - patches/fix_cwd_name_on_win.patch          # [win]
    - patches/skip-fastmath-test.patch           # [aarch64]
    # For some reason Linux-x86 fails the comparison checks on patched tests
    - patches/comment-out-linux-x86-tests.patch  # [linux and x86]       
    - patches/fix-problematic-gtests.patch       # [unix]       

build:
  number: 0
  skip: true  # [py<311]
  string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ ep_variant }}
  ignore_run_exports:
    - numpy
    - libcurl
  entry_points:
    - onnxruntime_test = onnxruntime.tools.onnxruntime_test:main
  missing_dso_whitelist:
    - '**/api-ms-win-core-path-l1-1-0.dll'     # [win]
    # For some reason discovered by conda as $RPATH/onnxruntime_providers_shared.dll
    # while the dumpbin shows just the name, and the file is installed to the same dir
    - '**/onnxruntime_providers_shared.dll'    # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [(ep_variant == "cuda")]
    - cmake
    - ninja-base
  host:
    - gtest
    - gmock
    # GPU requirements
    - cuda-nvcc {{ cuda_compiler_version }}        # [(ep_variant == "cuda")]
    - cudnn {{ cudnn }}                            # [(ep_variant == "cuda")]
    - cuda-version {{ cuda_compiler_version }}     # [(ep_variant == "cuda")]
    - libcublas-dev {{ cuda_compiler_version }}    # [(ep_variant == "cuda")]
    - libcurand-dev {{ libcurand }}                # [(ep_variant == "cuda")]
    - libcusparse-dev {{ libcusparse }}            # [(ep_variant == "cuda")]
    - libcufft-dev {{ libcufft }}                  # [(ep_variant == "cuda")]
    - cuda-cudart-dev {{ cuda_compiler_version }}  # [(ep_variant == "cuda")]
    - cuda-nvrtc-dev {{ cuda_compiler_version }}   # [(ep_variant == "cuda")]
    # Needed for CUDA profiling
    - cuda-cupti-dev {{ cuda_compiler_version }}   # [(ep_variant == "cuda")]
    - pip
    - python
    - setuptools
    - wheel
    - libdate 3.0.1
    - packaging
    - optional-lite 3.5.0
    - zlib {{ zlib }}
    - numpy {{ numpy }}
    - pybind11 2.13
    - psutil
  run:
    - coloredlogs
    # numpy 2.0 sets the min pin to 1.19 and 2.1 sets 1.21 but upstream requires at least 1.21.6
    - numpy >=1.21.6,<3
    - packaging
    - protobuf
    - python
    - python-flatbuffers
    - sympy
  run_constrained:
    - onnxruntime <0a0  # [suffix == "-novec"]

outputs:
  - name: onnxruntime{{ suffix }}
    files:
      include:
        - 'lib/python*/site-packages/onnxruntime/**'
        - 'lib/python*/site-packages/onnxruntime-{{ version }}.dist-info/**'
    test:
      imports:
        - onnxruntime
      commands:
        - pip check
        - onnxruntime_test --help
      requires:
        - pip
  - name: onnxruntime{{ suffix }}-cpp
    build:
      string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ ep_variant }}
      missing_dso_whitelist:
        - '**/api-ms-win-core-path-l1-1-0.dll'   # [win]
        - '**/onnxruntime_providers_shared.dll'  # [win]
      run_exports:
        - {{ pin_subpackage('onnxruntime' + suffix + '-cpp', max_pin='x.x.x') }}
    script: build.sh  # [unix]
    script: bld.bat   # [win]
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}  # [(ep_variant == "cuda")]
      host:
        - libcudnn-dev {{ cudnn }}                     # [(ep_variant == "cuda")]
        - libcufft-dev {{ libcufft }}                  # [(ep_variant == "cuda")]
        - libcublas-dev {{ cuda_compiler_version }}    # [(ep_variant == "cuda")]
        - cuda-cupti-dev {{ cuda_compiler_version }}   # [(ep_variant == "cuda")]
        - cuda-cudart-dev {{ cuda_compiler_version }}  # [(ep_variant == "cuda")]
      run_constrained:
        - onnxruntime <0a0       # [suffix == "-novec"]
    test:                        # [(ep_variant == "cpu")]
      requires:                  # [(ep_variant == "cpu")]
        - {{ stdlib('c') }}      # [(ep_variant == "cpu")]
        - {{ compiler('cxx') }}  # [(ep_variant == "cpu")]
      files:                     # [(ep_variant == "cpu")]
        - test.cpp               # [(ep_variant == "cpu")]
        - run_cpp_test.bat       # [(ep_variant == "cpu")]
      commands:                  # [(ep_variant == "cpu")]
        - test -f $PREFIX/include/onnxruntime/core/session/onnxruntime_cxx_api.h  # [unix and (ep_variant == "cpu")]
        - test -f $PREFIX/lib/libonnxruntime${SHLIB_EXT}                          # [unix and (ep_variant == "cpu")]
        # - test -f $PREFIX/lib/libonnxruntime_providers_shared${SHLIB_EXT}  # [unix and (ep_variant == "cuda")]
        # - test -f $PREFIX/lib/libonnxruntime_providers_cuda${SHLIB_EXT}    # [unix and (ep_variant == "cuda")]
        - if not exist %LIBRARY_INC%\\onnxruntime\\core\\session\\onnxruntime_cxx_api.h exit 1  # [win and (ep_variant == "cpu")]
        - if not exist %LIBRARY_LIB%\\onnxruntime_conda.lib exit 1                              # [win and (ep_variant == "cpu")]
        - if not exist %LIBRARY_BIN%\\onnxruntime_conda.dll exit 1                              # [win and (ep_variant == "cpu")]
        # - if not exist %LIBRARY_LIB%\\onnxruntime_providers_shared.lib exit 1  # [win and (ep_variant == "cuda")]
        # - if not exist %LIBRARY_BIN%\\onnxruntime_providers_shared.dll exit 1  # [win and (ep_variant == "cuda")]
        # - if not exist %LIBRARY_LIB%\\onnxruntime_providers_cuda.lib exit 1    # [win and (ep_variant == "cuda")]
        # - if not exist %LIBRARY_BIN%\\onnxruntime_providers_cuda.dll exit 1    # [win and (ep_variant == "cuda")]
        - $CXX $CXXFLAGS -I$PREFIX/include/ -L$PREFIX/lib/ -lonnxruntime test.cpp                               # [linux and (ep_variant == "cpu")]
        - $CXX $CXXFLAGS -I$PREFIX/include/ -L$PREFIX/lib/ -lonnxruntime -Wl,-rpath,$CONDA_PREFIX/lib test.cpp  # [osx and (ep_variant == "cpu")]
        - ./a.out                  # [unix and (ep_variant == "cpu")]
        - call .\run_cpp_test.bat  # [win and (ep_variant == "cpu")]

about:
  home: https://onnxruntime.ai
  license: MIT AND BSL-1.0
  license_family: MIT
  license_file: LICENSE
  summary: cross-platform, high performance ML inferencing and training accelerator
  description: |
    ONNX Runtime is a cross-platform machine-learning model accelerator,
    with a flexible interface to integrate hardware-specific libraries.
    ONNX Runtime can be used with models from PyTorch, Tensorflow/Keras,
    TFLite, scikit-learn, and other frameworks.
  dev_url: https://github.com/microsoft/onnxruntime
  doc_url: https://onnxruntime.ai/docs

extra:
  recipe-maintainers:
    - xhochy
    - janjagusch
    - jtilly
    - cbourjau
  skip-lints:
    - missing_section
    - outputs_not_unique
    - patch_unnecessary
